In [185]:
import pandas as pd
train = pd.read_csv("/Users/juhn/Desktop/stady_file/資料整理/SCoML/train.csv",encoding = "utf-8")
test = pd.read_csv("/Users/juhn/Desktop/stady_file/資料整理/SCoML/test.csv",encoding = "utf-8")

In [186]:
test.isna().sum().sum()

np.int64(47376)

In [187]:
def Clean_Number_None(df):
    median = df.median(numeric_only=True)
    df = df.fillna(median)
    return df

train = Clean_Number_None(train)
test = Clean_Number_None(test)

In [188]:
train.isna().sum()

encounter_id                     0
patient_id                       0
hospital_id                      0
age                              0
bmi                              0
                              ...
lymphoma                         0
solid_tumor_with_metastasis      0
apache_3j_bodysystem           907
apache_2_bodysystem            907
hospital_death                   0
Length: 84, dtype: int64

In [189]:
for col in train.columns:
    if (train[col].isna().sum() > 0):
        most = train[col].value_counts().idxmax()
        train[col] = train[col].fillna(most)
train.isna().sum().sum()

np.int64(0)

In [190]:
for col in test.columns:
    if test[col].isna().sum() > 0:
        most = test[col].value_counts().idxmax()
        test[col] = test[col].fillna(most)

In [191]:
test.isna().sum().sum()

np.int64(0)

In [192]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51359 entries, 0 to 51358
Data columns (total 84 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   encounter_id                   51359 non-null  int64
 1   patient_id                     51359 non-null  int64
 2   hospital_id                    51359 non-null  int64
 3   age                            51359 non-null  float64
 4   bmi                            51359 non-null  float64
 5   elective_surgery               51359 non-null  int64
 6   ethnicity                      51359 non-null  object
 7   gender                         51359 non-null  object
 8   height                         51359 non-null  float64
 9   icu_admit_source               51359 non-null  object
 10  icu_id                         51359 non-null  int64
 11  icu_stay_type                  51359 non-null  object
 12  icu_type                       51359 non-null  object
 13  pre_icu_los_days               51359 non-null  float64
 14  weight                         51359 non-null  float64
 15  apache_2_diagnosis             51359 non-null  float64
 16  apache_3j_diagnosis            51359 non-null  float64
 17  apache_post_operative          51359 non-null  int64
 18  arf_apache                     51359 non-null  float64
 19  gcs_eyes_apache                51359 non-null  float64
 20  gcs_motor_apache               51359 non-null  float64
 21  gcs_unable_apache              51359 non-null  float64
 22  gcs_verbal_apache              51359 non-null  float64
 23  heart_rate_apache              51359 non-null  float64
 24  intubated_apache               51359 non-null  float64
 25  map_apache                     51359 non-null  float64
 26  resprate_apache                51359 non-null  float64
 27  temp_apache                    51359 non-null  float64
 28  ventilated_apache              51359 non-null  float64
 29  d1_diasbp_max                  51359 non-null  float64
 30  d1_diasbp_min                  51359 non-null  float64
 31  d1_diasbp_noninvasive_max      51359 non-null  float64
 32  d1_diasbp_noninvasive_min      51359 non-null  float64
 33  d1_heartrate_max               51359 non-null  float64
 34  d1_heartrate_min               51359 non-null  float64
 35  d1_mbp_max                     51359 non-null  float64
 36  d1_mbp_min                     51359 non-null  float64
 37  d1_mbp_noninvasive_max         51359 non-null  float64
 38  d1_mbp_noninvasive_min         51359 non-null  float64
 39  d1_resprate_max                51359 non-null  float64
 40  d1_resprate_min                51359 non-null  float64
 41  d1_spo2_max                    51359 non-null  float64
 42  d1_spo2_min                    51359 non-null  float64
 43  d1_sysbp_max                   51359 non-null  float64
 44  d1_sysbp_min                   51359 non-null  float64
 45  d1_sysbp_noninvasive_max       51359 non-null  float64
 46  d1_sysbp_noninvasive_min       51359 non-null  float64
 47  d1_temp_max                    51359 non-null  float64
 48  d1_temp_min                    51359 non-null  float64
 49  h1_diasbp_max                  51359 non-null  float64
 50  h1_diasbp_min                  51359 non-null  float64
 51  h1_diasbp_noninvasive_max      51359 non-null  float64
 52  h1_diasbp_noninvasive_min      51359 non-null  float64
 53  h1_heartrate_max               51359 non-null  float64
 54  h1_heartrate_min               51359 non-null  float64
 55  h1_mbp_max                     51359 non-null  float64
 56  h1_mbp_min                     51359 non-null  float64
 57  h1_mbp_noninvasive_max         51359 non-null  float64
 58  h1_mbp_noninvasive_min         51359 non-null  float64
 59  h1_resprate_max                51359 non-null  float64
 60  h1_resprate_min                51359 non-null  float64
 61  h1_spo2_max                    51359 non-null  float64
 62  h1_spo2_min                    51359 non-null  float64
 63  h1_sysbp_max                   51359 non-null  float64
 64  h1_sysbp_min                   51359 non-null  float64
 65  h1_sysbp_noninvasive_max       51359 non-null  float64
 66  h1_sysbp_noninvasive_min       51359 non-null  float64
 67  d1_glucose_max                 51359 non-null  float64
 68  d1_glucose_min                 51359 non-null  float64
 69  d1_potassium_max               51359 non-null  float64
 70  d1_potassium_min               51359 non-null  float64
 71  apache_4a_hospital_death_prob  51359 non-null  float64
 72  apache_4a_icu_death_prob       51359 non-null  float64
 73  aids                           51359 non-null  float64
 74  cirrhosis                      51359 non-null  float64
 75  diabetes_mellitus              51359 non-null  float64
 76  hepatic_failure                51359 non-null  float64
 77  immunosuppression              51359 non-null  float64
 78  leukemia                       51359 non-null  float64
 79  lymphoma                       51359 non-null  float64
 80  solid_tumor_with_metastasis    51359 non-null  float64
 81  apache_3j_bodysystem           51359 non-null  object
 82  apache_2_bodysystem            51359 non-null  object
 83  hospital_death                 51359 non-null  int64
dtypes: float64(70), int64(7), object(7)
memory usage: 32.9+ MB

In [193]:
train_Encoder = pd.get_dummies(train["gender"]).astype("int64")
train = pd.concat([train,train_Encoder],axis=1)
train = train.drop("gender",axis=1)

test_Encoder = pd.get_dummies(test["gender"]).astype("int64")
test = pd.concat([test,test_Encoder],axis=1)
test = test.drop("gender",axis=1)

In [194]:
Encoder = pd.get_dummies(train["apache_3j_bodysystem"]).astype("int64")
train = pd.concat([train,Encoder],axis=1)
train = train.drop("apache_3j_bodysystem",axis=1)

Encoder = pd.get_dummies(test["apache_3j_bodysystem"]).astype("int64")
test = pd.concat([test,Encoder],axis=1)
test = test.drop("apache_3j_bodysystem",axis=1)

test

,encounter_id,patient_id,hospital_id,age,bmi,elective_surgery,ethnicity,height,icu_admit_source,icu_id,...,Gastrointestinal,Genitourinary,Gynecological,Hematological,Metabolic,Musculoskeletal/Skin,Neurological,Respiratory,Sepsis,Trauma
0,13622,58481,125,87.0,28.506234,0,Caucasian,175.20,Accident & Emergency,696,...,0,0,0,0,0,0,0,0,1,0
1,3289,115023,19,58.0,33.719008,0,Caucasian,165.00,Accident & Emergency,657,...,0,1,0,0,0,0,0,0,0,0
2,72644,47360,76,79.0,21.512459,0,Hispanic,142.20,Floor,256,...,0,0,0,0,0,0,0,1,0,0
3,1643,80391,133,63.0,39.088978,0,Caucasian,167.60,Floor,561,...,0,0,0,0,0,0,0,1,0,0
4,45345,29625,196,60.0,23.876499,0,Caucasian,195.59,Accident & Emergency,809,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22006,62127,114868,70,64.0,34.141137,0,Caucasian,162.00,Accident & Emergency,451,...,0,0,0,0,0,0,1,0,0,0
22007,68261,118852,111,24.0,45.052505,0,African American,163.00,Floor,602,...,0,1,0,0,0,0,0,0,0,0
22008,81375,118711,194,52.0,30.449827,0,Caucasian,170.00,Accident & Emergency,607,...,0,0,0,0,0,0,0,0,0,0
22009,103579,36672,21,57.0,33.763293,0,Caucasian,172.70,Accident & Emergency,508,...,0,0,0,0,0,0,0,0,1,0
22010,112184,105538,13,31.0,24.579931,0,Caucasian,165.10,Floor,694,...,0,0,0,0,0,0,1,0,0,0

In [195]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51359 entries, 0 to 51358
Data columns (total 95 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   encounter_id                   51359 non-null  int64
 1   patient_id                     51359 non-null  int64
 2   hospital_id                    51359 non-null  int64
 3   age                            51359 non-null  float64
 4   bmi                            51359 non-null  float64
 5   elective_surgery               51359 non-null  int64
 6   ethnicity                      51359 non-null  object
 7   height                         51359 non-null  float64
 8   icu_admit_source               51359 non-null  object
 9   icu_id                         51359 non-null  int64
 10  icu_stay_type                  51359 non-null  object
 11  icu_type                       51359 non-null  object
 12  pre_icu_los_days               51359 non-null  float64
 13  weight                         51359 non-null  float64
 14  apache_2_diagnosis             51359 non-null  float64
 15  apache_3j_diagnosis            51359 non-null  float64
 16  apache_post_operative          51359 non-null  int64
 17  arf_apache                     51359 non-null  float64
 18  gcs_eyes_apache                51359 non-null  float64
 19  gcs_motor_apache               51359 non-null  float64
 20  gcs_unable_apache              51359 non-null  float64
 21  gcs_verbal_apache              51359 non-null  float64
 22  heart_rate_apache              51359 non-null  float64
 23  intubated_apache               51359 non-null  float64
 24  map_apache                     51359 non-null  float64
 25  resprate_apache                51359 non-null  float64
 26  temp_apache                    51359 non-null  float64
 27  ventilated_apache              51359 non-null  float64
 28  d1_diasbp_max                  51359 non-null  float64
 29  d1_diasbp_min                  51359 non-null  float64
 30  d1_diasbp_noninvasive_max      51359 non-null  float64
 31  d1_diasbp_noninvasive_min      51359 non-null  float64
 32  d1_heartrate_max               51359 non-null  float64
 33  d1_heartrate_min               51359 non-null  float64
 34  d1_mbp_max                     51359 non-null  float64
 35  d1_mbp_min                     51359 non-null  float64
 36  d1_mbp_noninvasive_max         51359 non-null  float64
 37  d1_mbp_noninvasive_min         51359 non-null  float64
 38  d1_resprate_max                51359 non-null  float64
 39  d1_resprate_min                51359 non-null  float64
 40  d1_spo2_max                    51359 non-null  float64
 41  d1_spo2_min                    51359 non-null  float64
 42  d1_sysbp_max                   51359 non-null  float64
 43  d1_sysbp_min                   51359 non-null  float64
 44  d1_sysbp_noninvasive_max       51359 non-null  float64
 45  d1_sysbp_noninvasive_min       51359 non-null  float64
 46  d1_temp_max                    51359 non-null  float64
 47  d1_temp_min                    51359 non-null  float64
 48  h1_diasbp_max                  51359 non-null  float64
 49  h1_diasbp_min                  51359 non-null  float64
 50  h1_diasbp_noninvasive_max      51359 non-null  float64
 51  h1_diasbp_noninvasive_min      51359 non-null  float64
 52  h1_heartrate_max               51359 non-null  float64
 53  h1_heartrate_min               51359 non-null  float64
 54  h1_mbp_max                     51359 non-null  float64
 55  h1_mbp_min                     51359 non-null  float64
 56  h1_mbp_noninvasive_max         51359 non-null  float64
 57  h1_mbp_noninvasive_min         51359 non-null  float64
 58  h1_resprate_max                51359 non-null  float64
 59  h1_resprate_min                51359 non-null  float64
 60  h1_spo2_max                    51359 non-null  float64
 61  h1_spo2_min                    51359 non-null  float64
 62  h1_sysbp_max                   51359 non-null  float64
 63  h1_sysbp_min                   51359 non-null  float64
 64  h1_sysbp_noninvasive_max       51359 non-null  float64
 65  h1_sysbp_noninvasive_min       51359 non-null  float64
 66  d1_glucose_max                 51359 non-null  float64
 67  d1_glucose_min                 51359 non-null  float64
 68  d1_potassium_max               51359 non-null  float64
 69  d1_potassium_min               51359 non-null  float64
 70  apache_4a_hospital_death_prob  51359 non-null  float64
 71  apache_4a_icu_death_prob       51359 non-null  float64
 72  aids                           51359 non-null  float64
 73  cirrhosis                      51359 non-null  float64
 74  diabetes_mellitus              51359 non-null  float64
 75  hepatic_failure                51359 non-null  float64
 76  immunosuppression              51359 non-null  float64
 77  leukemia                       51359 non-null  float64
 78  lymphoma                       51359 non-null  float64
 79  solid_tumor_with_metastasis    51359 non-null  float64
 80  apache_2_bodysystem            51359 non-null  object
 81  hospital_death                 51359 non-null  int64
 82  F                              51359 non-null  int64
 83  M                              51359 non-null  int64
 84  Cardiovascular                 51359 non-null  int64
 85  Gastrointestinal               51359 non-null  int64
 86  Genitourinary                  51359 non-null  int64
 87  Gynecological                  51359 non-null  int64
 88  Hematological                  51359 non-null  int64
 89  Metabolic                      51359 non-null  int64
 90  Musculoskeletal/Skin           51359 non-null  int64
 91  Neurological                   51359 non-null  int64
 92  Respiratory                    51359 non-null  int64
 93  Sepsis                         51359 non-null  int64
 94  Trauma                         51359 non-null  int64
dtypes: float64(70), int64(20), object(5)
memory usage: 37.2+ MB

In [196]:
Encoder = pd.get_dummies(train["icu_type"]).astype("int64")
train = pd.concat([train,Encoder],axis=1)
train = train.drop("icu_type",axis=1)

Enocder = pd.get_dummies(test["icu_type"]).astype("int64")
test = pd.concat([test,Enocder],axis=1)
test = test.drop("icu_type",axis=1)

In [197]:
test

,encounter_id,patient_id,hospital_id,age,bmi,elective_surgery,ethnicity,height,icu_admit_source,icu_id,...,Sepsis,Trauma,CCU-CTICU,CSICU,CTICU,Cardiac ICU,MICU,Med-Surg ICU,Neuro ICU,SICU
0,13622,58481,125,87.0,28.506234,0,Caucasian,175.20,Accident & Emergency,696,...,1,0,0,0,0,0,0,1,0,0
1,3289,115023,19,58.0,33.719008,0,Caucasian,165.00,Accident & Emergency,657,...,0,0,1,0,0,0,0,0,0,0
2,72644,47360,76,79.0,21.512459,0,Hispanic,142.20,Floor,256,...,0,0,0,0,0,0,0,1,0,0
3,1643,80391,133,63.0,39.088978,0,Caucasian,167.60,Floor,561,...,0,0,0,0,0,0,0,1,0,0
4,45345,29625,196,60.0,23.876499,0,Caucasian,195.59,Accident & Emergency,809,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22006,62127,114868,70,64.0,34.141137,0,Caucasian,162.00,Accident & Emergency,451,...,0,0,0,0,0,0,0,0,1,0
22007,68261,118852,111,24.0,45.052505,0,African American,163.00,Floor,602,...,0,0,0,0,0,0,0,1,0,0
22008,81375,118711,194,52.0,30.449827,0,Caucasian,170.00,Accident & Emergency,607,...,0,0,0,0,0,1,0,0,0,0
22009,103579,36672,21,57.0,33.763293,0,Caucasian,172.70,Accident & Emergency,508,...,1,0,0,0,0,0,0,1,0,0
22010,112184,105538,13,31.0,24.579931,0,Caucasian,165.10,Floor,694,...,0,0,0,0,0,0,0,1,0,0

In [198]:
def drop_data(df)->any:
    df = df.drop(["encounter_id","patient_id","hospital_id"],axis=1)
    return df
train = drop_data(train)
test = drop_data(test)
train

,age,bmi,elective_surgery,ethnicity,height,icu_admit_source,icu_id,icu_stay_type,pre_icu_los_days,weight,...,Sepsis,Trauma,CCU-CTICU,CSICU,CTICU,Cardiac ICU,MICU,Med-Surg ICU,Neuro ICU,SICU
0,72.0,34.111992,0,Other/Unknown,154.0,Accident & Emergency,377,admit,-0.112500,80.9,...,0,0,0,0,0,0,0,1,0,0
1,70.0,29.469745,0,African American,173.0,Accident & Emergency,608,admit,0.097222,88.2,...,0,0,0,0,0,0,0,1,0,0
2,42.0,30.456041,1,Caucasian,185.5,Operating Room / Recovery,869,admit,0.026389,104.8,...,0,0,0,0,0,0,0,1,0,0
3,66.0,32.247402,1,Caucasian,165.1,Operating Room / Recovery,683,admit,1.035417,87.9,...,0,0,0,0,0,0,0,1,0,0
4,57.0,32.623321,0,Caucasian,172.7,Operating Room / Recovery,434,transfer,0.516667,97.3,...,1,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51354,58.0,38.027312,0,Hispanic,172.0,Operating Room / Recovery,489,admit,0.239583,112.5,...,0,0,0,0,0,0,0,1,0,0
51355,88.0,34.532157,0,Caucasian,167.6,Accident & Emergency,505,admit,0.024306,97.0,...,0,0,0,0,0,0,0,1,0,0
51356,53.0,35.528961,1,Caucasian,167.6,Operating Room / Recovery,498,admit,1.178472,99.8,...,0,0,0,0,0,0,0,1,0,0
51357,58.0,27.746939,1,Caucasian,180.3,Operating Room / Recovery,491,admit,8.259722,90.2,...,0,0,0,0,0,0,0,1,0,0
51358,47.0,34.510930,0,Caucasian,157.4,Accident & Emergency,707,admit,0.159722,85.5,...,0,0,0,0,0,0,0,1,0,0

In [199]:
def OneHotEncoder(df,s):
    Encoder = pd.get_dummies(df[s]).astype("int64")
    df = pd.concat([df,Encoder],axis=1)
    df = df.drop(s,axis=1)
    return df

train = OneHotEncoder(train,"ethnicity")
test = OneHotEncoder(test,"ethnicity")

In [200]:
train

,age,bmi,elective_surgery,height,icu_admit_source,icu_id,icu_stay_type,pre_icu_los_days,weight,apache_2_diagnosis,...,MICU,Med-Surg ICU,Neuro ICU,SICU,African American,Asian,Caucasian,Hispanic,Native American,Other/Unknown
0,72.0,34.111992,0,154.0,Accident & Emergency,377,admit,-0.112500,80.9,124.0,...,0,1,0,0,0,0,0,0,0,1
1,70.0,29.469745,0,173.0,Accident & Emergency,608,admit,0.097222,88.2,105.0,...,0,1,0,0,1,0,0,0,0,0
2,42.0,30.456041,1,185.5,Operating Room / Recovery,869,admit,0.026389,104.8,304.0,...,0,1,0,0,0,0,1,0,0,0
3,66.0,32.247402,1,165.1,Operating Room / Recovery,683,admit,1.035417,87.9,213.0,...,0,1,0,0,0,0,1,0,0,0
4,57.0,32.623321,0,172.7,Operating Room / Recovery,434,transfer,0.516667,97.3,113.0,...,1,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51354,58.0,38.027312,0,172.0,Operating Room / Recovery,489,admit,0.239583,112.5,214.0,...,0,1,0,0,0,0,0,1,0,0
51355,88.0,34.532157,0,167.6,Accident & Emergency,505,admit,0.024306,97.0,124.0,...,0,1,0,0,0,0,1,0,0,0
51356,53.0,35.528961,1,167.6,Operating Room / Recovery,498,admit,1.178472,99.8,213.0,...,0,1,0,0,0,0,1,0,0,0
51357,58.0,27.746939,1,180.3,Operating Room / Recovery,491,admit,8.259722,90.2,308.0,...,0,1,0,0,0,0,1,0,0,0
51358,47.0,34.510930,0,157.4,Accident & Emergency,707,admit,0.159722,85.5,114.0,...,0,1,0,0,0,0,1,0,0,0

In [201]:
train["icu_admit_source"]

0             Accident & Emergency
1             Accident & Emergency
2        Operating Room / Recovery
3        Operating Room / Recovery
4        Operating Room / Recovery
                   ...
51354    Operating Room / Recovery
51355         Accident & Emergency
51356    Operating Room / Recovery
51357    Operating Room / Recovery
51358         Accident & Emergency
Name: icu_admit_source, Length: 51359, dtype: object

In [202]:
def flow_name(s):
    name = s.split(" ")[-1]
    name = name.replace(" ","")
    return name
train["icu_admit_source"] = train["icu_admit_source"].apply(flow_name)

In [203]:
train = OneHotEncoder(train,"icu_admit_source")
train

,age,bmi,elective_surgery,height,icu_id,icu_stay_type,pre_icu_los_days,weight,apache_2_diagnosis,apache_3j_diagnosis,...,Asian,Caucasian,Hispanic,Native American,Other/Unknown,Emergency,Floor,Hospital,ICU,Recovery
0,72.0,34.111992,0,154.0,377,admit,-0.112500,80.9,124.0,305.02,...,0,0,0,0,1,1,0,0,0,0
1,70.0,29.469745,0,173.0,608,admit,0.097222,88.2,105.0,207.01,...,0,0,0,0,0,1,0,0,0,0
2,42.0,30.456041,1,185.5,869,admit,0.026389,104.8,304.0,1408.07,...,0,1,0,0,0,0,0,0,0,1
3,66.0,32.247402,1,165.1,683,admit,1.035417,87.9,213.0,1405.04,...,0,1,0,0,0,0,0,0,0,1
4,57.0,32.623321,0,172.7,434,transfer,0.516667,97.3,113.0,501.04,...,0,1,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51354,58.0,38.027312,0,172.0,489,admit,0.239583,112.5,214.0,1401.01,...,0,0,1,0,0,0,0,0,0,1
51355,88.0,34.532157,0,167.6,505,admit,0.024306,97.0,124.0,306.01,...,0,1,0,0,0,1,0,0,0,0
51356,53.0,35.528961,1,167.6,498,admit,1.178472,99.8,213.0,1405.02,...,0,1,0,0,0,0,0,0,0,1
51357,58.0,27.746939,1,180.3,491,admit,8.259722,90.2,308.0,1207.01,...,0,1,0,0,0,0,0,0,0,1
51358,47.0,34.510930,0,157.4,707,admit,0.159722,85.5,114.0,102.01,...,0,1,0,0,0,1,0,0,0,0